### ISSUE TITLE
a question about your code

### ISSUE THREAD

**Issue by pppiap** [PatrickStaehli/delay_and_sum_matlab_gpu_mex#1]
sorry, i'm new in this field and i can't understand what's the 'iter' in line 105 and line 141~143, can you tell me? thank you very much

**Comment by PatrickStaehli** [comment]
Hi pppiap
This refers to the full global thread ID. Since we launch N kernels, which is equalt to the number of pixels we reconstruct, this refers to the 1D index of the reconstructed image.
In line 141 to 143, i decompose this 1D index to the 3D coordinates of the to be reconstructed pixel (z,x,angle).
